### ISSUE TITLE
Node 12 seems to be required

### ISSUE THREAD

**Issue by knuch** [frontend/toolbox-utils#36] opened 2019-05-14 12:45 UTC
Is node 12 required to build a project with toolbox from now on? 

I did fiddle a bit to find out that switching to node 12 after having deleted my `node_modules` folder, and after updating everything made my projet usable again.

Could be good to display a message if the user is not using the correct node version when using the project

**Comment by tonifisler** [comment] 2019-05-21 08:45
This needs to be fixed in `package.json` then, it says node 6 is a minimum.
https://github.com/frontend/toolbox-utils/blob/d17e47d9f50aff804c17b26e436510b280ecf016/package.json#L6-L8

**Comment by tonifisler** [comment] 2019-05-21 08:47
Actually, this is a duplicate of #28 😉 

Closing in favor of it.

**Closed by tonifisler** 2019-05-21 08:47 UTC
